global using CommunityToolkit.Maui;
global using Finjanz.Pages;
global using Finjanz.Resources.Styles;
global using Finjanz.Shell;
global using Finjanz.State;
global using Microsoft.Maui;
global using Microsoft.Maui.Hosting;
global using Microsoft.Maui.Graphics;
global using MauiControls = Microsoft.Maui.Controls;
global using MauiReactor;
global using MauiReactor.Shapes;